sudo: true
dist: xenial
jobs:
  include:
    - language: ruby
      rvm:
        - 2.4.5
        - 2.5.3
        - 2.6.1
      env:
        - SKIP_RPC_TESTS=true
      cache: 
        - bundler
      before_install: 
        - cd server
        - gem install bundler -v 2.0.1
        - sudo apt-get update
        - sudo apt-get install -y libsodium-dev
      install:
        - bundle install
      script:
        - bundle exec rake


    - language: node_js
      node_js:
        - '11.10'
      cache:
        - npm
        - yarn
      before_install:
        - cd web
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - travis_retry yarn install
      script:
        - yarn build
        - yarn test